### ISSUE TITLE
Provide shell script for build verification steps

### ISSUE THREAD

**Issue by stefanscheidt** [rewe-digital/schema2000#110]
When I want to verify a branch locally on my machine before I create a PR, I have to submit quite a bunch of commands. 

It would be nice to have one or two shell scripts to do this verification. One shell script could do the necessary installations on the local machine - maybe optional - the second one - more important - would do the actual verification.

It would be great if we restructure the GitHub build workflow to also use this shell script.

See also #53 and #109.

**Comment by elmarx** [comment]
+1 for Justfile, see PR.

Providing a Justfile is what came to my mind, too, when I read your slack conversation :)
